import { spawnSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const SITE_DIR = fileURLToPath(new URL("..", import.meta.url));
const SERVER_DIR = path.join(SITE_DIR, "../server");
const OUT = path.join(SITE_DIR, "content/docs/policy-reference.mdx");

interface Row {
  name: string;
  type: string;
  default: unknown;
  description: string;
}

interface Dump {
  fields: Row[];
  presets: Record<string, Record<string, unknown>>;
  summaries: Record<string, string>;
}

const PY = `
import json, sys
sys.path.insert(0, ".")
from app.policy import PRESET_OVERRIDES, PRESET_SUMMARY, policy_schema
print(json.dumps({"fields": policy_schema(), "presets": PRESET_OVERRIDES, "summaries": PRESET_SUMMARY}))
`;

function dumpFromServer(): Dump {
  const attempts: [string, string[]][] = [
    ["uv", ["run", "--no-sync", "python", "-c", PY]],
    ["python3", ["-c", PY]],
  ];
  for (const [cmd, args] of attempts) {
    const r = spawnSync(cmd, args, { cwd: SERVER_DIR, encoding: "utf8", env: { ...process.env, WEIGHTS_DIR: "weights" } });
    if (r.status === 0 && r.stdout.trim()) return JSON.parse(r.stdout.trim().split("\n").at(-1)!) as Dump;
  }
  throw new Error("cannot import server/app/policy.py: install uv or python3 with pydantic and pydantic-settings");
}

function cell(v: unknown) {
  return `\`${JSON.stringify(v)}\``;
}

function fieldRows(rows: Row[]) {
  return rows.map((r) => `| \`${r.name}\` | ${r.type} | ${cell(r.default)} | ${r.description} |`).join("\n");
}

function flattenOverrides(o: Record<string, unknown>, prefix = ""): [string, unknown][] {
  return Object.entries(o).flatMap(([k, v]) =>
    v && typeof v === "object" && !Array.isArray(v) ? flattenOverrides(v as Record<string, unknown>, `${prefix}${k}.`) : [[`${prefix}${k}`, v]],
  );
}

function presetSection(dump: Dump) {
  return Object.entries(dump.presets)
    .map(([name, overrides]) => {
      const rows = flattenOverrides(overrides);
      const table = rows.length
        ? `| Field | Value |\n|---|---|\n${rows.map(([k, v]) => `| \`${k}\` | ${cell(v)} |`).join("\n")}`
        : "_No overrides: the environment defaults as they are._";
      return `### ${name}\n\n${dump.summaries[name]}\n\n${table}`;
    })
    .join("\n\n");
}

const dump = dumpFromServer();
const server = dump.fields.filter((f) => !f.name.startsWith("client."));
const client = dump.fields.filter((f) => f.name.startsWith("client."));
const mdx = `---
title: Policy reference
description: Every field a project can tune, generated from server/app/policy.py. Set them with PUT /v1/policy or as environment defaults.
---

{/* generated by website/scripts/generate-policy-reference.ts; do not edit by hand */}

A policy is resolved per request as **environment defaults → preset → project overrides**. Server fields are applied by the verification pipeline; \`client.*\` fields are sent to the app in every session as \`client_config\` and applied by the Flutter and React SDKs while running the challenges. Any field can be overridden:

\`\`\`bash
curl -X PUT $SERVER/v1/policy -H "X-API-Key: $KEY" -H "Content-Type: application/json" \\
  -d '{"preset": "strict", "overrides": {"match_threshold": 0.5, "client": {"challenge_timeout_ms": 8000}}}'
\`\`\`

The same names, upper-cased, are the environment variables that set the defaults of the \`balanced\` preset (server fields only; client defaults live in the code).

## Server fields

| Field | Type | Default | Description |
|---|---|---|---|
${fieldRows(server)}

## Client fields

| Field | Type | Default | Description |
|---|---|---|---|
${fieldRows(client)}

## Presets

Each preset is a set of overrides on top of the environment defaults. \`GET /v1/policy/presets\` returns the same data with the fully resolved policy per preset.

${presetSection(dump)}
`;
writeFileSync(OUT, mdx);
console.log(`wrote ${OUT} (${dump.fields.length} fields)`);
